# Лабораторная работа №3

ФИО: Поляховская Ольга Александровна  
Группа: БИВТ-22-СП-2

Отправлять можно следующими способами:
1. Запушить этот ноутбук в GitHub в репозиторий, где у вас лежат ноутбуки с лабами

Deadlines:
- Занятие №7 в семестре (Занятие №3 очное)

Что необходимо сделать:  
- Обучить различного рода модели машинного обучения и сравнить их между собой  

---
## Читайте задание внимательно

Исходные данные:
1. В [табличке](https://docs.google.com/spreadsheets/d/1k2MYXEp_OVQrink_XRC1PwoM0ZuNMeNz4VTWY7cI3hE/edit?usp=sharing) необходимо узнать название своего датасета 
2. Скачать нужны вам данные можно в [Google Drive](https://drive.google.com/drive/folders/1Phm-Fq1GL-VX7NS-DCEMRh_Fo1wU7DQ9?usp=sharing)
  
---
Теперь по пунктам, что я от вас жду:  
1. Загрузить необходимые данные к себе и считать (read) их в переменную.
2. Понять, у вас задача классификации (бинарной или многоклассовой) или регрессии (**если у вас многоклассовая классификация, прочтите P.S.S. внизу**).
3. Сделать предобработку данных:  
     1. Разделить выборку на тренировочную (train) и тестовую (test). _Обратите внимание, что обучать скейлеры и определять, какими значениями вы будете заполнять пропуски, вы будете на train выборке, а применять и на train, и на test_.
     2. Проверить пропуски в данных. Если они есть, заполнить одной из стратегий, предложенных в ноутбуке для семинара №3. P.S. Для численных и категориальных переменных будут разные стратегии.
     3. Отнормировать численные переменные (`StandardScaler`, `MinMaxScaler`).
     4. Закодировать категориальные признаки по одной из стратегий.
4. Обучить на тренировочном множестве:
     1. Линейную модель (`LogisticRegression`, `LinearRegression`)
     2. Деревянную модель (`DecisionTreeClassifier`, `DecisionTreeRegressor`) (тут советую попробовать разные глубины деревьев)
     3. K-ближайших соседей (`KNeighborsClassifier`, `KNeighborsRegressor`) (тут тоже есть смысл попробовать разные `k`)
     4. Случайный лес (`RandomForestClassifier`, `RandomForestRegressor`) 
5. Посчитайте метрики на train и test множествах:
     1. Для задачи классификации -- Accuracy, ROC-AUC (график + значение), PR-кривую (график), F1-score
     2. Для задачи регрессии -- MAE, RMSE, MAPE
6. Сравните метрики относительно train/test, так и относительно разных моделей. Ответьте на следующие вопросы:
     1. Какая модель справилась лучше с поставленной задачей?
     2. Имеет ли место переобучение?
     3. Имеет ли место недообучение?
     4. Как можно улучшить метрики моделей?


## 1. Пример импорта данных. Грузим данные

In [ ]:
import pandas as pd
import math as m
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelEncoder

data = pd.read_csv('winequality-red.csv', sep=',')

data.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [30]:
print(f'Уникальные значения целевой переменной: {data["quality"].nunique()}')
print(f'Размерность датасета: {data.shape}')

Уникальные значения целевой переменной: 6
Размерность датасета: (1599, 12)


## 2. Понимаем, какая перед нами задача

### Цель
Разработать модель машинного обучения для предсказания оценки красного вина на основе его химического состава и особенностях приготовления
### Переменные
#### Целевая переменная
- `quality`: оценка вина, которую дали сомелье. Диапазон от 3 до 8

#### Признаки
- `fixed acidity`: Кислота 
- `volatile acidity`: Кислота
- `citric acid`: Содержание лимонной кислоты в вине
- `residual sugar`: Значение содержания остаточного сахара в вине
- `chlorides`: Процент содержания хлоридов
- `free sulfur dioxide`: 
- `density`: Плотность вина
- `pH`: Значение pH кислотности вина
- `sulphates`: Процент содержания сульфатов в вине
- `alcohol`: Процент содержания алкоголя в вине
### Задача
Перед нами стоит задача регрессии

## 3. Делаем предобработку данных

Проверить пропуски в данных

In [31]:
print(f'Пропуски в колонках датасета:\n{data.isnull().sum()}')

Пропуски в колонках датасета:
fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64


Нормирование численных переменных

In [ ]:
for elem in data.keys():
	data[elem] = MinMaxScaler().fit_transform(data[elem].values.reshape(-1, 1))
data

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0          0.247788          0.397260         0.00        0.068493   0.106845   
1          0.283186          0.520548         0.00        0.116438   0.143573   
2          0.283186          0.438356         0.04        0.095890   0.133556   
3          0.584071          0.109589         0.56        0.068493   0.105175   
4          0.247788          0.397260         0.00        0.068493   0.106845   
...             ...               ...          ...             ...        ...   
1594       0.141593          0.328767         0.08        0.075342   0.130217   
1595       0.115044          0.294521         0.10        0.089041   0.083472   
1596       0.150442          0.267123         0.13        0.095890   0.106845   
1597       0.115044          0.359589         0.12        0.075342   0.105175   
1598       0.123894          0.130137         0.47        0.184932   0.091820   

      free sulfur dioxide  total sulfur dioxide   density        pH  \
0                0.140845              0.098940  0.567548  0.606299   
1                0.338028              0.215548  0.494126  0.362205   
2                0.197183              0.169611  0.508811  0.409449   
3                0.225352              0.190813  0.582232  0.330709   
4                0.140845              0.098940  0.567548  0.606299   
...                   ...                   ...       ...       ...   
1594             0.436620              0.134276  0.354626  0.559055   
1595             0.535211              0.159011  0.370778  0.614173   
1596             0.394366              0.120141  0.416300  0.535433   
1597             0.436620              0.134276  0.396476  0.653543   
1598             0.239437              0.127208  0.397944  0.511811   

      sulphates   alcohol  quality  
0      0.137725  0.153846      0.4  
1      0.209581  0.215385      0.4  
2      0.191617  0.215385      0.4  
3      0.149701  0.215385      0.6  
4      0.137725  0.153846      0.4  
...         ...       ...      ...  
1594   0.149701  0.323077      0.4  
1595   0.257485  0.430769      0.6  
1596   0.251497  0.400000      0.6  
1597   0.227545  0.276923      0.4  
1598   0.197605  0.400000      0.6  

[1599 rows x 12 columns]

Разделение выборки на тренировочную и тестовую

In [34]:
from sklearn.model_selection import train_test_split

x = data[['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides', 'free sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol']].values

y = data['quality'].values

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3)

print(f'Тренировочная выборка x:\n{x_train}\n')
print(f'Тренировочная выборка y:\n {y_train}\n')
print(f'Тестовая выборка x:\n {x_test}\n')
print(f'Тестовая выборка y:\n {y_test}\n')

Тренировочная выборка x:
[[0.17699115 0.42123288 0.02       ... 0.57480315 0.11976048 0.23076923]
 [0.53982301 0.15753425 0.53       ... 0.32283465 0.19161677 0.4       ]
 [0.17699115 0.33561644 0.         ... 0.46456693 0.0239521  0.30769231]
 ...
 [0.37168142 0.3869863  0.26       ... 0.45669291 0.08383234 0.15384615]
 [0.15929204 0.39041096 0.         ... 0.57480315 0.11976048 0.69230769]
 [0.38053097 0.24657534 0.24       ... 0.28346457 0.11976048 0.12307692]]

Тренировочная выборка y:
 [0.4 1.  0.2 ... 0.4 0.6 0.4]

Тестовая выборка x:
 [[0.68141593 0.18493151 0.63       ... 0.33070866 0.09580838 0.16923077]
 [0.2300885  0.3630137  0.02       ... 0.73228346 0.28143713 0.2       ]
 [0.20353982 0.31506849 0.2        ... 0.50393701 0.09580838 0.50769231]
 ...
 [0.08849558 0.54452055 0.         ... 0.74015748 0.23952096 0.46153846]
 [0.37168142 0.21917808 0.49       ... 0.44094488 0.16167665 0.16923077]
 [0.61946903 0.23972603 0.44       ... 0.50393701 0.31736527 0.23076923]]

Тестова

## 4. Обучаем на тренировочном множестве

Линейная модель

In [35]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lr.fit(x_train, y_train)

lr_pred_test = lr.predict(x_test)
lr_pred_train = lr.predict(x_train)

Деревянная модель

In [36]:
from sklearn.tree import DecisionTreeRegressor

tree = DecisionTreeRegressor(max_depth = 10)
tree.fit(x_train, y_train)

tree_pred_test = tree.predict(x_test)
tree_pred_train = tree.predict(x_train)

К ближайших соседей

In [37]:
from sklearn.neighbors import KNeighborsRegressor

knn = KNeighborsRegressor()
knn.fit(x_train, y_train)

knn_pred_test = knn.predict(x_test)
knn_pred_train = knn.predict(x_train)

Случайный лес

In [48]:
from sklearn.ensemble import RandomForestRegressor

rfr = RandomForestRegressor()
rfr.fit(x_train, y_train)

rfr_pred_test = rfr.predict(x_test)
rfr_pred_train = rfr.predict(x_train)

## 5. Считаем метрики на train и test множесвах(MAE, rmse, MAPE)

In [ ]:
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error

def errors(y, pred):
	mae = mean_absolute_error(y, pred)
	rmse = mean_squared_error(y, pred)**0.5
	y, pred = np.array(y), np.array(pred)
	non_zero_indices = y != 0
	mape = np.mean(np.abs((y[non_zero_indices] - pred[non_zero_indices]) / y[non_zero_indices]))*100
	print(f'MAE = {mae:.2f}; RMSE = {rmse:.2f}; MAPE = {mape}')
	return

print(f'\nМетрики линейной модели:\n На тестовой выборке:')
errors(y_test, lr_pred_test)
print(f'На тренировочной выборке:')
errors(y_train, lr_pred_train)

print(f'\nМетрики деревянной модели:\n На тестовой выборке:')
errors(y_test, tree_pred_test)
print(f'На тренировочной выборке:')
errors(y_train, tree_pred_train)

print(f'\nМетрики К ближайших соседей модели:\n На тестовой выборке:')
errors(y_test, knn_pred_test)
print(f'На тренировочной выборке:')
errors(y_train, knn_pred_train)

print(f'\nМетрики модели случайный лес:\n На тестовой выборке:')
errors(y_test, rfr_pred_test)
print(f'На тренировочной выборке:')
errors(y_train, rfr_pred_train)


Метрики линейной модели:
 На тестовой выборке:
MAE = 0.10; RMSE = 0.13; MAPE = 22.466815433980262
На тренировочной выборке:
MAE = 0.10; RMSE = 0.13; MAPE = 21.00853477091247

Метрики деревянной модели:
 На тестовой выборке:
MAE = 0.09; RMSE = 0.15; MAPE = 20.343194895327578
На тренировочной выборке:
MAE = 0.03; RMSE = 0.06; MAPE = 6.766638722203484

Метрики К ближайших соседей модели:
 На тестовой выборке:
MAE = 0.11; RMSE = 0.14; MAPE = 23.03835425383544
На тренировочной выборке:
MAE = 0.08; RMSE = 0.11; MAPE = 17.62736273627364

Метрики модели случайный лес:
 На тестовой выборке:
MAE = 0.09; RMSE = 0.12; MAPE = 18.912691771269163
На тренировочной выборке:
MAE = 0.03; RMSE = 0.05; MAPE = 6.744104410441004


## 6. Сравниваем метрики относительно train/test, так и относительно разных моделей.

1. Какая модель справилась лучше с поставленной задачей?

	Меньше всего различий в метриках у линейной модели, поэтому она справилась лучше других
2. Имеет ли место переобучение?

	Большинство моделей имеют более низкие метрики на тренировочной выборке, чем на тестовой, т.е. модели переобучены.
3. Имеет ли место недообучение?

	Метрики модели К ближайших соседей довольно высокие, а на тренировочной выборке ниже тестовой, поэтому недообучение вполне может быть
4. Как можно улучшить метрики моделей?

	Использовать больше данных на обучении
	Провести более тщательную предобработку параметров